### ISSUE TITLE
Error registering an add-on: unable to find add-on metadata file

### ISSUE THREAD

**Issue by vezza** [RenanMsV/landing_rate#1]
Flightgear 2018.2.0

addon-metadata.xml file missing

Error message:
Error registering an add-on: unable to find add-on metadata file 'fg_addons_path/landing_rate/addon-metadata.xml'

**Comment by RenanMsV** [comment]
Thanks.
Pascal ( polin1962 ) fixed the addon for the 2018 version. You can find it at https://github.com/pascal-olin/landing_rate
