### ISSUE TITLE
Support addon-hints so aircraft can optionally specify own definitions of "good"/"bad"

### ISSUE THREAD

**Issue by hbeni** [RenanMsV/landing_rate#6]
Hi,
right now the categories for good/bad are hardcoded in the addon.
This is not suitable for all aircraft, for example you can break the gear of the C172p and still get "acceptable" (which it is clearly not :smile: ).

It would be cool, it the aircraft.xml could specify hints for the addon like this:
```xml
<sim>
    <addon-hints>
        <landing_rate>
                <ranks>
                        <bad>
                            <min-fpm>150</min-fpm>
                        </bad>
                        <acceptable>
                            <min-fpm>100</min-fpm>
                        </acceptable>
                        <good>
                            <min-fpm>75</min-fpm>
                        </good>
                        <very-good>
                            <min-fpm>50</min-fpm>
                        </very-good>
                        <!-- excellent is fine and need not to be overwritten -->
                </ranks>
        </landing_rate>
    </addon-hints>
</sim>
```

If present, these could override the hardcoded settings.

**Comment by RenanMsV** [comment]
A very good idea. Furthermore, it has the potential to expand the use of the addon.

Does the current version of Flightgear 2020.3.19 supports addon-hints already?

**Comment by hbeni** [comment]
> Does the current version of Flightgear 2020.3.19 supports addon-hints already?

Yes, it should. Its just properties in the tree, provided by the aircraft.xml
