### ISSUE TITLE
Make sharemp dynamic parameter (read by property) + GUI

### ISSUE THREAD

**Issue by hbeni** [RenanMsV/landing_rate#8]
> To enable it go to landing_rate folder and open addon-config.xml. Find sharemp line.
> <sharemp>0</sharemp>
> Change sharemp value (1 for yes and 0 for no). Restart your simulator. Done.

It would be nice if:

- [x] `<sharemp>` would be dynamically read from a property below `/addons/by-id/landing_rate`
- [x] default to `false`
- [x] setting to `true` therefore would, from that point onwards, share it in the chat. Setting to `false` again would disable sharing from that point onwards.
- [x] a small config GUI would provide access to that property for normal users.
- [x] correct readme.md 

```nasal
# Init GUI menu entry
    var menuTgt = "/sim/menubar/default/menu[7]";  # 7=multiplayer
    var menudata = {
		label   : "Landing Rate",
		name    : "landing_rate",
		binding : { command : "dialog-show", "dialog-name" : "landing_rate_settings" }
	};
	props.globals.getNode(menuTgt).addChild("item").setValues(menudata);
	fgcommand("gui-redraw");
```
Re: the menu bar index; I believe there is a standardized "Addons" menu index we should use.

**Comment by hbeni** [comment]
Ah, okay; just have seen that just the documentation is "wrong/misleading".

The prop is already exposed in `/addons/by-id/..../addon-devel/sharemp`.

So just the GUI is missing to access that conviniently.

**Comment by RenanMsV** [comment]
For that we could add a dialog with addon-menubar-items.xml.
As described here https://wiki.flightgear.org/Addon#Additional_common_files

**Comment by RenanMsV** [comment]
I have just added a pull request to add the settings dialog.
https://github.com/RenanMsV/landing_rate/pull/9
